spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://i9a403.p.ssafy.io/soyun
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true #To beautify or pretty print the SQL
        show_sql: true #show sql

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 576948301615-8ufadev53dgsclrt6ssobvbnmksbg2cl.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

logging:
  level:
    org.hibernate:
      type.descriptor.sql: trace #show parameter binding
      SQL: DEBUG

server:
  servlet:
    session:
      tracking-modes: cookie